import assert from "node:assert/strict";
import { createGoIndex } from "../../navigation/go/goIndex.js";
import type { GoTarget } from "../../navigation/go/fileMapping.js";

const sampleGoCode = `// Code generated by protoc-gen-go. DO NOT EDIT.
package v1

type BookArchive struct {
	id string
}

type Book struct {
	state protoimpl.MessageState
}

type BookState int32

type BookServiceServer interface {
	CreateBook(context.Context, *CreateBookRequest) (*CreateBookResponse, error)
	mustEmbedUnimplementedBookServiceServer()
}

func (UnimplementedBookServiceServer) CreateBook(context.Context, *CreateBookRequest) (*CreateBookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBook not implemented")
}
`;

describe("GoIndex", () => {
  const index = createGoIndex();

  it("finds message declaration (type Book struct)", () => {
    const target: GoTarget = {
      filePath: "/path/to/book.pb.go",
      symbolName: "Book",
      kind: "message"
    };

    const loc = index.find(sampleGoCode, target);
    assert(loc);
    assert.equal(loc.line, 7);
    assert.equal(loc.startCharacter, 5); // "type Book struct" -> "Book" is at index 5
    assert.equal(loc.endCharacter, 9);
  });

  it("respects symbol boundaries and does not match BookArchive for Book", () => {
    const target: GoTarget = {
      filePath: "/path/to/book.pb.go",
      symbolName: "Book",
      kind: "message"
    };

    const loc = index.find(sampleGoCode, target);
    assert(loc);
    assert.equal(loc.line, 7); // Not line 3 (BookArchive)
  });

  it("finds enum declaration (type BookState int32)", () => {
    const target: GoTarget = {
      filePath: "/path/to/book.pb.go",
      symbolName: "BookState",
      kind: "enum"
    };

    const loc = index.find(sampleGoCode, target);
    assert(loc);
    assert.equal(loc.line, 11);
    assert.equal(loc.startCharacter, 5);
    assert.equal(loc.endCharacter, 14);
  });

  it("finds service interface declaration (type BookServiceServer interface)", () => {
    const target: GoTarget = {
      filePath: "/path/to/book_grpc.pb.go",
      symbolName: "BookService",
      kind: "service"
    };

    const loc = index.find(sampleGoCode, target);
    assert(loc);
    assert.equal(loc.line, 13);
    assert.equal(loc.startCharacter, 5); // "type BookServiceServer interface {" -> "BookServiceServer" is at index 5
    assert.equal(loc.endCharacter, 22); // 5 + 17 ("BookServiceServer".length)
  });

  it("finds rpc method declaration inside the service interface", () => {
    const target: GoTarget = {
      filePath: "/path/to/book_grpc.pb.go",
      symbolName: "CreateBook",
      kind: "rpc",
      parentService: "BookService"
    };

    const loc = index.find(sampleGoCode, target);
    assert(loc);
    assert.equal(loc.line, 14); // Line inside BookServiceServer interface
    assert.equal(loc.startCharacter, 1); // "\tCreateBook(" -> index 1
    assert.equal(loc.endCharacter, 11);
  });

  it("does not match rpc implementation method outside service interface", () => {
    const target: GoTarget = {
      filePath: "/path/to/book_grpc.pb.go",
      symbolName: "CreateBook",
      kind: "rpc",
      parentService: "OtherService"
    };

    const loc = index.find(sampleGoCode, target);
    assert.equal(loc, undefined);
  });

  it("handles CRLF line endings", () => {
    const crlfCode = sampleGoCode.replace(/\n/gu, "\r\n");
    const target: GoTarget = {
      filePath: "/path/to/book.pb.go",
      symbolName: "Book",
      kind: "message"
    };

    const loc = index.find(crlfCode, target);
    assert(loc);
    assert.equal(loc.line, 7);
    assert.equal(loc.startCharacter, 5);
    assert.equal(loc.endCharacter, 9);
  });

  it("returns undefined when cancelled before scanning", () => {
    const target: GoTarget = {
      filePath: "/path/to/book.pb.go",
      symbolName: "Book",
      kind: "message"
    };

    const loc = index.find(sampleGoCode, target, () => true);
    assert.equal(loc, undefined);
  });

  it("checks cancellation every 128 lines during scanning", () => {
    const largeCode = sampleGoCode + "\n".repeat(300);
    const target: GoTarget = {
      filePath: "/path/to/book.pb.go",
      symbolName: "NonExistent",
      kind: "message"
    };

    let checkCount = 0;
    const loc = index.find(largeCode, target, () => {
      checkCount++;
      return checkCount > 2;
    });

    assert.equal(loc, undefined);
    assert(checkCount >= 2);
  });

  it("escapes regex special characters in symbol names", () => {
    const codeWithSpecialChars = `type Book$Special struct {}\n`;
    const target: GoTarget = {
      filePath: "/path/to/book.pb.go",
      symbolName: "Book$Special",
      kind: "message"
    };

    const loc = index.find(codeWithSpecialChars, target);
    assert(loc);
    assert.equal(loc.line, 0);
    assert.equal(loc.startCharacter, 5);
    assert.equal(loc.endCharacter, 17);
  });
});
